name: "setting up Nodejs Environment"

on:
  push:
    branches:
      - master
      - main

env:
  MONGO_URI: ${{ secrets.MONGO_URI }}
  PORT: ${{ secrets.PORT }}
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
  EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
  EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
  EMAIL_USER: ${{ secrets.EMAIL_USER }}
  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
  OTP_EXPIRY_MINUTES: ${{ secrets.OTP_EXPIRY_MINUTES }}

jobs:
  setting_up_nodejs:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "21"
        
      - name: "Check Node version"
        run: node --version

      - name: "Install dependencies"
        run: npm install

      - name: "Install Nodemon in VM"
        run: npm install nodemon

      - name: "Start the server"
        run: node server.js
